name: 'Actions AWS backend setup'
description: 'Search or Create Terraform backend resources on AWS'
inputs:
  instance: 
    description: 'Unique identifier for infrastructure'
    required: true
    default: 'tf-backend'
outputs:
  s3:
    description: "Backend S3 name"
    value: ${{ steps.s3.outputs.name }}  
  dynamodb:
    description: "Backend dynamodb Table"
    value: ${{ steps.kms.outputs.name }}  
runs:
  using: "composite"
  steps:
    - name: query dynamodb
      shell: bash
      id: dynamodb
      env: 
        SERVICE: dynamodb
      run: | 
        arn=$(aws resourcegroupstaggingapi get-resources \
          --tag-filters Key=tf-backend,Values=true \
          --resource-type-filters $SERVICE \
          --query "ResourceTagMappingList[].ResourceARN" \
          --output text)
        echo "arn=$arn" >> $GITHUB_OUTPUT
        name=$(echo "$arn" | awk -F ':::' '{print $2}')
        echo "name=$name" >> $GITHUB_OUTPUT
    - name: query s3
      shell: bash
      id: s3
      env: 
        SERVICE: s3
      run: | 
        arn=$(aws resourcegroupstaggingapi get-resources \
          --tag-filters Key=tf-backend,Values=true \
          --resource-type-filters $SERVICE \
          --query "ResourceTagMappingList[].ResourceARN" \
          --output text)
        echo "arn=$arn" >> $GITHUB_OUTPUT
        name=$(echo "$arn" | awk -F ':::' '{print $2}')
        echo "name=$name" >> $GITHUB_OUTPUT